.env.local.example
=> DIGG-8: Add env vars to connect to prod data

.gitignore, Dockerfile, README.md, package.json, yarn.lock
=> Digg 90 main

.env.local.example
=> DIGG-70: Update env example file with info regarding apollo router

components/content/blocks/AccordionBlock/index.tsx, components/content/blocks/BlockList/index.tsx
Updating width for accordion as well
=> DIGG-62-beta: Updating aria labels for accordion

components/Navigation/ContainerNav/index.tsx, components/Navigation/SideBar/index.tsx, components/content/ContainerPage/index.tsx, components/global/Typography/HtmlParser/index.tsx, components/layout/Header/index.tsx, pages/_app.tsx, tailwind.config.js
Fixed padding on header, adding margins to headings in text-blocks
=> DIGG-67-beta: Removing resize and scroll eventlistner on sidebar and containerNav

.env.local.example, utilities/generateCsp.ts
=> Digg 10 beta

.env.production, graphql/client.ts, utilities/queryHelpers.ts
=> Prod settings

.env.production, graphql/client.ts, utilities/queryHelpers.ts
Reverts diggsweden/dataportal-web#210
=> Revert "Prod settings"

.env.production
=> set revalidate cache interval

graphql/client.ts
=> set default cache options for apollo client to cache-and-network

utilities/queryHelpers.ts
=> remove fetch policy override

utilities/queryHelpers.ts
Reverts diggsweden/dataportal-web#216
=> Revert "remove fetch policy override"

.env.production, .gitlab-ci.yml
=> Set apollo url

.gitlab-ci.yml
=> add variable name

.gitlab-ci.yml
=> Set image domain

next.config.js
=> add config for staticPageGenerationTimeout

utilities/generateCsp.ts
=> add new domain

components/global/CustomImage/index.tsx
=> removed query string witdh and quality from next image declaration

components/content/DomainPage/index.tsx, components/content/blocks/RelatedContentBlock/index.tsx
Updating datasamverkan label E-hälso initiativet to Hälsa, vård och omsorg
=> DIGG-242: updating e hälso block title

.env.local.example, components/content/Publication/PublicationTeaser/index.tsx, components/content/blocks/MediaBlock/index.tsx, components/global/CustomImage/index.tsx, components/global/Typography/HtmlParser/index.tsx, components/layout/Hero/index.tsx, next.config.js
Updating image optimization through Next for external images
=> Hotfix image optimize

next.config.js
=> fixed a false statement in how we read env variable for image domain

components/global/Typography/HtmlParser/index.tsx, components/navigation/ContainerNav/index.tsx, components/navigation/MainNav/index.tsx, components/navigation/SideBar/index.tsx, components/navigation/SkipToContent/index.tsx, hooks/useClickoutside.ts, pages/_app.tsx, styles/base.css
Navigation fixes for click outside, focus state and updating styling on first header on text block
=> Digg 279 beta

pages/api/healthcheck.ts
=> Digg 314 beta

components/global/CustomImage/index.tsx
=> Fixing linting

components/global/MetaData/index.tsx
=> DIGG-257: changed to follow and index by seach engins

components/content/Entryscape/DataSetPage/index.tsx, locales/en/pages.json, locales/sv/pages.json, providers/EntrystoreProvider/index.tsx
=> DIGG-383: Related specifications

components/navigation/MainNav/index.tsx, components/navigation/TopNav/index.tsx, tailwind.config.js
=> DIGG-345:Colors, lang  and aria label

components/layout/Footer/index.tsx
=> DIGG-356: Update alt text for footer EU logo

components/global/MetaData/index.tsx
=> DIGG-457: Add google site verification meta tag in HTML head

utilities/generateCsp.ts
=> DIGG-456: Add more csp rules for matomo

next.config.js, utilities/generateCsp.ts
=> DIGG-465: Matomo script add

next.config.js, utilities/generateCsp.ts
=> DIGG-465: prodOnly false

utilities/generateCsp.ts
=> DIGG-456: Updating CSP rules

components/content/Search/SearchResults/index.tsx, providers/EntrystoreProvider/index.tsx, utilities/entryScape.ts, utilities/entrystoreUtil.ts
=> DIGG-452: Updating search result list to show the publisher in the current language

README.md, env/Settings.Dev.ts, env/Settings.Prod.ts
=> DIGG-461: editera => admin

utilities/generateCsp.ts
=> DIGG-456: Add entrystore.js script to scp under 'script-src-elem'.

components/content/Search/SearchForm/index.tsx, components/content/Search/SearchInput/index.tsx, components/content/Search/SearchPage/SearchContentPage/index.tsx, components/content/Search/SearchResults/index.tsx, components/global/Form/TextInput/index.tsx, components/layout/Hero/index.tsx, components/navigation/MainNav/index.tsx, locales/en/common.json, locales/sv/common.json
=> DIGG-349: Updating search to be screen reader accessible

components/content/Entryscape/ConceptPage/index.tsx, components/content/Entryscape/SpecificationPage/index.tsx, components/content/Search/SearchPage/SearchPageEntryScape/index.tsx, components/content/Search/SearchResults/index.tsx, pages/externalconcept/[...concept].tsx, pages/externalconcept/index.tsx, pages/externalspecification/index.tsx, pages/externalterminology/[...terminology].tsx, pages/externalterminology/index.tsx, utilities/entryscape_blocks.ts
=> DIGG-443: Updating external concept, terminology and specification to use query parameter

components/content/Entryscape/ConceptPage/index.tsx, components/content/Entryscape/DataSetPage/index.tsx, components/content/Entryscape/DatasetExploreApiPage/index.tsx, components/content/Entryscape/SpecificationPage/index.tsx, components/content/Search/SearchFilters/SearchFilter/index.tsx, components/content/blocks/AccordionBlock/index.tsx, components/global/Form/RenderForm/index.tsx, components/navigation/ContainerNav/index.tsx, components/navigation/FormNav/index.tsx, components/navigation/MainNav/index.tsx, components/navigation/SideBar/index.tsx, hooks/useClickoutside.ts, styles/entryscape.css, styles/entryscapeMQA.css
=> DIGG-358: Updating aria attributes on toggle buttons and fixing clickoutside

components/navigation/SkipToContent/index.tsx
=> DIGG-359: Updating skip to content button to link

components/navigation/MainNav/index.tsx, styles/base.css
=> DIGG-363: Logotype white in High Contrast mode

components/content/Entryscape/ConceptPage/index.tsx, tailwind.config.js
=> DIGG-460: Updating font size sm to 15px

utilities/generateCsp.ts
=> DIGG-456: Add screen9 amper player js to script-src-elem

components/global/CookieBanner/index.tsx
=> DIGG-377: Removing cookie id because brave seems to override it

components/content/Search/GlobalSearch/index.tsx, components/content/Search/SearchInput/index.tsx, components/content/Search/SearchPage/SearchTestPage/index.tsx
=> DIGG-350: Removing autocomplete off on search inputs

components/global/ProgressBar/index.tsx
=> DIGG-355: Updating accessibility on form progress bar

Dockerfile, README.md, README.swe.md
=> DIGG-473: Update node version to 22

components/navigation/MainNav/index.tsx
=> DIGG-473: Update code formatting

yarn.lock
=> DIGG-473: Update yarn.lock

Dockerfile
=> DIGG-473: try setting correct yarn version globally

components/content/Search/SearchFilters/index.tsx, components/content/Search/SearchPage/SearchPageEntryScape/index.tsx, components/content/Search/SearchResults/index.tsx, package.json, providers/SearchProvider/index.tsx, types/entrystore-js.d.ts, types/search.d.ts, utilities/entryScape.ts, utilities/entrystoreUtil.ts, utilities/generateCsp.ts, utilities/localCache.ts, utilities/publisherCache.ts, yarn.lock
=> DIGG-463: Improving search implementation and caching organisation names

components/content/Entryscape/DataSetPage/index.tsx, pages/dataservice/[dataSet]/[name].tsx, pages/datasets/[dataSet]/[name]/apiexplore/[apieid].tsx, pages/datasets/[dataSet]/[name]/apiexplore/index.tsx, pages/datasets/[dataSet]/[name]/index.tsx, pages/datasets/[dataSet]/apiexplore/[apieid].tsx, utilities/entryScape.ts
=> DIGG-474: Updating url paths for datasets, dataservice and apiexplorer

components/content/Search/SearchResults/index.tsx
=> DIGG-466: Updating placement and styling for organisation name on search list

pages/organisations/[org]/index.tsx
=> DIGG-450: Fixing organisation page name

features/search/search-page/search-page-entryscape/search-page-provider-settings.ts, providers/entrystore-provider/index.tsx, types/entrystore-js.d.ts, utilities/entryscape/entryscape.ts
=> DIGG-450: Fixing search filter to exclude types instead of include

features/search/search-page/search-page-entryscape/search-page-provider-settings.ts, types/search.d.ts, utilities/entrystore/entrystore.service.ts
=> DIGG-512: Adding pathresolver

pages/concepts/[concept]/[param].tsx, pages/concepts/[concept]/index.tsx, pages/specifications/[spec]/[param].tsx, pages/specifications/[spec]/index.tsx, pages/terminology/[term]/[param].tsx, pages/terminology/[term]/index.tsx, utilities/entrystore/entrystore-redirect.ts
=> DIGG-512: Replacing static props with sever props

providers/entrystore-provider/index.tsx, utilities/entrystore/entrystore.service.ts
Adding specifications to concept and terminology page
=> DIGG-386: Adding specifications to concept page

features/entryscape/specification-page/index.tsx, locales/en/pages.json, locales/sv/pages.json, styles/entryscape.css
=> DIGG-513: Updating heading on specification page column

public/google26a7561c7ab98c58.html
=> DIGG-517: Adding google file for search verification

.github/workflows/cypress.yml, cypress/e2e/entryscape/concept-page.cy.ts, cypress/e2e/entryscape/dataset-page.cy.ts, cypress/e2e/entryscape/datasetseries-page.cy.ts, cypress/e2e/entryscape/organisation-page.cy.ts, cypress/e2e/entryscape/specification-page.cy.ts, cypress/e2e/entryscape/terminology-page.cy.ts, cypress/e2e/list-page/tools-and-support.cy.ts, cypress/e2e/search/search-concepts.cy.ts, cypress/e2e/search/search-datasets.cy.ts, cypress/e2e/search/search-organisations.cy.ts, cypress/e2e/search/search-specifications.cy.ts, cypress/e2e/start-page.cy.ts
Adding cypress workflow and also adding timeouts for all tests in case it takes a bit longer for the entryscape content to show.
=> DIGG-502: Adding cypress workflow

providers/entrystore-provider/index.tsx
=> DIGG-504: Opening up entryscape landingpages for indexing

features/search/search-page/search-page-entryscape/search-page-provider-settings.ts, types/entrystore-core.ts, types/entrystore-js.d.ts, types/search.d.ts, utilities/entrystore/entrystore.service.ts
Organisationslist should only include organisations that have a organisation page. These organisations has the same ID. (827) 
TICKET: [https://dgroupse.atlassian.net/browse/DIGG-531](url)
=> DIGG-531: Only include organisations with id = 827

components/navigation/top-nav/index.tsx, features/publication/publication-full/index.tsx
[https://dgroupse.atlassian.net/browse/DIGG-538](url)
=> DIGG-538: Accessibility report (namn, label & ids)

components/pagination/index.tsx, features/statistic/index.tsx, features/statistic/statistic-list-item/index.tsx, locales/en/pages.json, locales/sv/pages.json
[https://dgroupse.atlassian.net/browse/DIGG-537](url)
=> DIGG-537: Accessibility report (Meaningful content)

components/navigation/top-nav/index.tsx, features/publication/publication-full/index.tsx
=> DIGG-541: Accessibility report (namn, label & ids)

components/modal/index.tsx, features/tool/index.tsx
=> DIGG-539: Accessibility report (Tags / elements)

components/blocks/text-block/index.tsx, utilities/check-lang.tsx
Translate strings in text block heading
[https://dgroupse.atlassian.net/browse/DIGG-543](url)
=> DIGG-543: Translate strings in text block heading

utilities/entrystore/entrystore.service.ts
[https://dgroupse.atlassian.net/browse/DIGG-551](url)
=> DIGG-551: Disable JSONP

middleware.ts
=> BALDER-550: default english fix
